### ISSUE TITLE
The indent of content of text tag should not be changed

### ISSUE THREAD

**Issue by Vasilich** [RazrFalcon/svgcleaner#86]
if indenting is set to anything except "none", then text in text tag will be rendered as text with indent, that could even move it outside of viewbox.
`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" x="0px" y="0px" viewBox="0 0 34.06945 33.11168" enable-background="new 0 0 34.06945 33.11168" xml:space="preserve" id="svg2">
    <defs id="defs30"/>
    <text y="21.539351" x="5.6560216" style="font-size:18.9988308px;font-family:NotoSans" id="text13" font-size="18.99883px">IP</text>
</svg>`

For text tag the content should never change, so it should be somehow excluded from indenting.

**Comment by RazrFalcon** [comment]
`xml:space="preserve"` should be processed correctly. 

Could you provide before and after examples?

**Comment by Vasilich** [comment]
here the file that i have posted above, with result  after cleaning.
[Issue_TextElement.zip](https://github.com/RazrFalcon/svgcleaner/files/1036048/Issue_TextElement.zip)the thing is that the indent breaks it (by adding extra indent char left to the text content),  not space-preserve.

**Comment by RazrFalcon** [comment]
It's kinda fixed in the latest builds, because I removing `xml:space="preserve"` now (when possible).
But it's still a bug.

Text and XML are complete mess. For example, chrome shows both your images equally, but QtSvg and Inkscape - not...

**Comment by RazrFalcon** [comment]
I've released a new version. Try it.

**Comment by Vasilich** [comment]
I have tested new version. Inkscape renders both files to same bitmap, and that is already better.
But i think it is still wrong: in source file the content of the text element is "IP", and in cleaned file it is "\n\t\tIP\t" (C syntax). Can it be avoided to indent the content of tags if it is a text (and not child nodes)?

**Comment by RazrFalcon** [comment]
I have no idea how whitespaces should be handled. I can't find a good explanation, except [this one](https://www.w3.org/TR/SVG11/text.html#WhiteSpace).

> When xml:space="default", the SVG user agent will do the following using a copy of the original character data content. First, it will remove all newline characters. Then it will convert all tab characters into space characters. Then, it will strip off all leading and trailing space characters. Then, all contiguous space characters will be consolidated.

That's exactly what I do. But `preserve` doesn't handled very well. So there is room for improvement, but not in a way you want.

Also I can't keep an original whitespaces/indent while changing the indent.

**Comment by Vasilich** [comment]
OK, with xml space default everything works as it should (or at least the renderer can remove new characters to render it without changes).
But with preserve - "It will convert all newline and tab characters into space characters. "; and now Cleaner consolidates all leading and trailing tabs, what is actually wrong.

**Comment by RazrFalcon** [comment]
Yes. I will fix it.

**Comment by RazrFalcon** [comment]
Fixed by: https://github.com/RazrFalcon/libsvgdom/commit/2b0f1613ee609812545d110513bd98cd8da49c65

There is a complete rewrite of the text handling. Works much better now.

Try this build: [svgcleaner_win32_0.9.1.zip](https://github.com/RazrFalcon/svgcleaner/files/1077931/svgcleaner_win32_0.9.1.zip)

**Comment by Vasilich** [comment]
great work! 
now it works as expected/acc. to specs.
Thank you for fast response.

**Comment by RazrFalcon** [comment]
Glad to here it works as intended.
